# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paylater_Debtors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountHolderName', models.CharField(max_length=255)),
                ('Employer', models.CharField(max_length=255)),
                ('TotalDue', models.BigIntegerField()),
                ('Balance', models.BigIntegerField()),
                ('DaysInArrears', models.IntegerField()),
                ('MobilePhone', models.CharField(max_length=15)),
            ],
        ),
    ]
